<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <title>Slim3</title>

    <!-- Bootstrap core CSS -->
    <link href="<?= $base_url ?>/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= $base_url ?>/assets/css/custom.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pr&aacute;ctica II</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
           <li ><a href="<?= $base_url ?>">Prototipo Web</a></li>
            <li class="active"><a href="<?= $base_url."/api" ?>">Servicio Web</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container my_container"  >

		 <div class="panel panel-default">
		  <div class="panel-heading">			
		  	Servicio Web</div>
		  <div class="panel-body">
		  	<p> Se pone a disposici&oacute;n un servicio web para consultar empleados por rango de salario. <br/>
		  		 <small >Ejemplo: Empleados que tienen salario entre 1000 y 1500 USD.  <br/> 
		  		 	<i> <?= $base_url ?>/api/employees/get-by-range-salary?sal_min=<mark>1000</mark>&sal_max=<mark>1500</mark></i></small>
		  	</p>
		
		<form class="form-horizontal" target="_blank" action="<?= $base_url ?>/api/employees/get-by-range-salary"  >
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">Salario M&iacute;n.</label>
		    <div class="col-sm-10">
		      <input type="number" class="form-control" id="inputEmail3" value="" name="sal_min">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">Salario M&aacute;x.</label>
		    <div class="col-sm-10">
		      <input type="number" class="form-control" id="inputEmail3" value="" name="sal_max">
		    </div>
		  </div>
		  <div class="form-group">
		    <div class="col-sm-offset-2 col-sm-10">
		      <button type="submit" class="btn btn-default">Buscar</button>
		    </div>
		  </div>		  
		</form>
		
		  </div>
		</div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?= $base_url ?>/assets/js/jquery.min.js"></script>
    <script src="<?= $base_url ?>/assets/js/bootstrap.min.js"></script>    
  </body>
</html>
