<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <title>Slim3</title>

    <!-- Bootstrap core CSS -->
    <link href="<?= $base_url ?>/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= $base_url ?>/assets/css/custom.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pr&aacute;ctica II</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
           <li class="active"><a href="<?= $base_url ?>">Prototipo Web</a></li>
            <li><a href="<?= $base_url."/api" ?>">Servicio Web</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container my_container"  >

		 <div class="panel panel-default">
		  <div class="panel-heading">
			<a href="<?= $base_url."/employees" ?>" class="btn btn-default btn-xs">
				  <span class="glyphicon glyphicon-chevron-left"></span> Regresar
				</a>
				&nbsp;
		  	Detalle del Empleado</div>
		  <div class="panel-body">
		<?php if($result === false): ?>
		  	<div class="alert alert-warning">
			  <strong>Error!</strong> No se ha encontrado el empleado.
			</div>
		<?php else: ?>

		<form class="form-horizontal">
		  <div class="form-group">
		    <label for="inputEmail3" class="col-sm-2 control-label">Nombre</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="inputEmail3" readonly value="<?= $result["name"] ?>"  placeholder="Nombre">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">E-Mail</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="inputEmail3" readonly value="<?= $result["email"] ?>"  placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">Tel&eacute;fono</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="inputEmail3" readonly value="<?= $result["phone"] ?>"  placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">Direcci&oacute;n</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="inputEmail3" readonly value="<?= $result["address"] ?>"  placeholder="">
		    </div>
		  </div>
		   <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">Posici&oacute;n</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="inputEmail3" readonly value="<?= $result["position"] ?>"  placeholder="">
		    </div>
		  </div>
		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">Salario</label>
		    <div class="col-sm-10">
		      <input type="text" class="form-control" id="inputEmail3" readonly value="<?= $result["salary"] ?>"  placeholder="">
		    </div>
		  </div>
 		  <div class="form-group">
		    <label for="inputPassword3" class="col-sm-2 control-label">Habilidades</label>
		    <div class="col-sm-10">

		   <?php foreach ($result["skills"] as $key => $value): ?>
			   <label class="checkbox-inline">
				  <input type="checkbox" checked id="inlineCheckbox1" disabled > <?= $value["skill"] ?>
				</label>

		   <?php endforeach;?>
		    </div>
		  </div>
		 
		</form>
		
		<?php endif; ?>
			
		  </div>
		</div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?= $base_url ?>/assets/js/jquery.min.js"></script>
    <script src="<?= $base_url ?>/assets/js/bootstrap.min.js"></script>    
  </body>
</html>
