<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <title>Slim3</title>

    <!-- Bootstrap core CSS -->
    <link href="<?= $base_url ?>/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="<?= $base_url ?>/assets/css/custom.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pr&aacute;ctica II</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<?= $base_url ?>">Prototipo Web</a></li>
            <li><a href="<?= $base_url."/api" ?>">Servicio Web</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container my_container"  >

		 <div class="panel panel-default">
		  <div class="panel-heading">Listado de Empleados</div>
		  <div class="panel-body">
			<form class="form-horizontal" method="post" action="<?= $base_url."/employees/search_by_email" ?>">
				<div class="form-group">
					<label for="inputEmail3" class="col-sm-2 control-label">Buscar por E-mail</label>
					<div class="col-sm-8">
					  <input type="text" class="form-control" name="email" id="inputEmail3" placeholder="E-mail">
					</div>
					<div class="col-sm-2">
					  <button type="submit" class="btn btn-default">						
						  <span class="glyphicon glyphicon-search"></span> Buscar
						</button>
					</div>					
			    </div>			  
			</form>
		   <table class="table table-hover">
			<thead>
			  <tr>
				<th>Nombre</th>
				<th>E-Mail</th>
				<th>Posici&oacute;n</th>
				<th>Salario</th>
				<th>Ver</th>
			  </tr>
			</thead>
			<tbody>
			  <?php
			  	foreach ($result as $k => $v) :
			  ?>
			  <tr>
				<td><?= $v["name"] ?></td>				
				<td><?= $v["email"] ?></td>
				<td><?= $v["position"] ?></td>
				<td><?= $v["salary"] ?></td>
				<td>
				<a href="<?= $base_url ?>/employees/view/<?= $v["id"] ?>" class="btn btn-default btn-xs">
				  <span class="glyphicon glyphicon-eye-open"></span> Ver
				</a>
				</td>
			  </tr>
			  <?php
			  	endforeach;
			  ?>
			</tbody>
		  </table>
		  </div>
		</div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="<?= $base_url ?>/assets/js/jquery.min.js"></script>
    <script src="<?= $base_url ?>/assets/js/bootstrap.min.js"></script>    
  </body>
</html>
